name: test context variable using environment variables
on:
  push:
    branches: [feat-comment-to-issues]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: actions/checkout@v

      - name: Hello world
        run: |
          python3 main.py